name: Fetch Commit History

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  fetch-commit-history:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Get members of "gdsc" organization
        id: get-members
        run: |
          # 임시 더미데이터 사용
          members=("donggook-me")

      - name: Fetch commit history for each member
        id: fetch-commit-history
        run: |
          set -x
          
          all_commits=()
          
          for member in "${members[@]}"; do
            echo "Fetching commit history for $member..."
            member_commits=$(curl -sSL -H "Authorization: Bearer ${{ secrets.GH_TOKEN }}" "https://api.github.com/users/${member}/events")
      
            if [[ $(echo "$member_commits" | jq length) -gt 0 ]]; then
              all_commits+=("$member_commits")
            else
              echo "No new commit data for $member."
            fi
          done
      
          if [[ ${#all_commits[@]} -gt 0 ]]; then
            mkdir -p data
            timestamp=$(date +'%Y%m%d%H%M%S')
            echo "${all_commits[@]}" > data/commit_data_$timestamp.json
          else
            echo "No new commit data for any member." > data/empty_commit_data.txt
          fi


      


      - name: Commit and push fetched data to repository
        run: |
          cd $GITHUB_WORKSPACE
          git config user.email "actions@github.com"
          git config user.name "GitHub Actions"

          if [[ -n $(git status --porcelain) ]]; then
            git add data
            git commit -m "Update commit data"
            git push origin main
          fi
