name: Fetch Commit History

on:
  schedule:
    - cron: '*/10 * * * *'  # Run every day at midnight

jobs:
  fetch-commit-history:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Get members of "gdsc" organization
        id: get-members
        run: |
          members=$(curl -sSL -H "Authorization: Bearer ${{ secrets.GH_TOKEN }}" https://api.github.com/orgs/Google-DSC-Kookmin/members)
          echo "${members}" > members.json

      - name: Fetch commit history for each member
        id: fetch-commit-history
        run: |
          members=$(cat members.json | jq -r '.[].login')
          commit_data="{}"

          for member in $members; do
            member_id=$(curl -sSL -H "Authorization: Bearer ${{ secrets.GH_TOKEN }}" "https://api.github.com/users/${member}" | jq -r '.id')
            member_commits=$(curl -sSL -H "Authorization: Bearer ${{ secrets.GH_TOKEN }}" "https://api.github.com/users/${member}/events")
            if [[ $(echo "$member_commits" | jq length) -gt 0 ]]; then
              commit_data=$(echo "$commit_data" | jq --arg member "$member_id" --argjson commits "$member_commits" '. + { ($member): $commits }')
            fi
          done

          echo "$commit_data" > data/data.json

      - name: Commit and push fetched data to repository
        run: |
          cd $GITHUB_WORKSPACE
          git config user.email "actions@github.com"
          git config user.name "GitHub Actions"

          if [[ -n $(git status --porcelain) ]]; then
            git add data
            git commit -m "Update commit data"
            git push origin main
          fi
