name: Fetch Commit Data from External API

on:
  push:
    branches:
      - main  # Modify to the default branch name in your repository
  schedule:
    - cron: '*/5 * * * *'  # Run every 5 minutes

jobs:
  fetch-commit-data:
    runs-on: ubuntu-latest

    steps:
      - name: Fetch commit data from external API
        run: |
          # Use curl to fetch commit data from the external API
          curl -L \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer $GH_TOKEN" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/donggook-me/dkdev.github.io/commits > commit_data.json

      - name: Commit and push fetched data to repository
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git add commit_data.json
          git commit -m "Update commit data"
          git push origin main
